server:
  port: 8301

spring:
  application:
    name: FEBS-Gateway

eureka:
  instance:
    lease-renewal-interval-in-seconds: 20
  client:
    register-with-eureka: true
    fetch-registry: true
    instance-info-replication-interval-seconds: 30
    registry-fetch-interval-seconds: 3
    serviceUrl:
      defaultZone: http://febs:123456@localhost:8001/register/eureka/

zuul:
  routes:
    auth:
      path: /auth/**
      serviceId: FEBS-Auth
      sensitiveHeaders: "*"
    system:
      path: /system/**
      serviceId: FEBS-Server-System
      sensitiveHeaders: "*"
    test:
      path: /test/**
      serviceId: FEBS-Server-Test
      sensitiveHeaders: "*"
  retryable: true
  ignored-services: "*"
  ribbon:
    eager-load:
      enabled: true
  SendErrorFilter:
    error:
      disable: true
ribbon:
  ReadTimeout: 3000